# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 02:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wrinklr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchupGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='matchupguess',
            name='guess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wrinklr_app.Person'),
        ),
        migrations.AddField(
            model_name='matchupguess',
            name='matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wrinklr_app.Matchup'),
        ),
        migrations.AddField(
            model_name='matchupguess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchup',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person1', to='wrinklr_app.Person'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person2', to='wrinklr_app.Person'),
        ),
    ]
