# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wrinklr_app', '0003_auto_20160926_0226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchup',
            unique_together=set([('person1', 'person2')]),
        ),
        migrations.AlterUniqueTogether(
            name='matchupguess',
            unique_together=set([('matchup', 'user')]),
        ),
    ]
